### ISSUE TITLE
Bauen unter Linux

### ISSUE THREAD

**Issue by x29a** [pythklas/ahnenwin2gedcom#2]
Hallo,

erstmal vielen Dank fuer das Projekt, das klingt nach genau dem, was man benoetigt wenn man alte HEJ Dateien von Ahnenwin wiederbeleben moechte/soll.

Ich habe versucht das Projekt unter Linux zu bauen (kein Windows verfuegbar) und dazu einen maven/graalvm/native-image Docker Container verwendet

> docker run --rm -it -v $PWD:/mnt/myproject:rw -w /mnt/myproject vegardit/graalvm-maven:latest-java11 mvn clean package -Pnative-image

(oder eben dem executable jar Profil).

Das Compilen und auch die Tests scheinen einwandfrei zu funktionieren, beim native-image findet er jedoch die Main class nicht 

`
Error: Main entry point class 'de.ng.ahnenwin2gedcom.Application' neither found on the classpath nor on the modulepath
`

und beim executable jar sowas aehnliches.

```
$ java -cp ahnenwin-2-gedcom-1.3-SNAPSHOT.jar de.ng.ahnenwin2gedcom.Application
Error: Could not find or load main class de.ng.ahnenwin2gedcom.Application
Caused by: java.lang.ClassNotFoundException: de.ng.ahnenwin2gedcom.Application
```

Hat irgendwer Tipps wie ich die Software zum Laufen bekommen koennte?

Danke und Lg

**Comment by x29a** [comment]
Ok, kaum schreibt man sich was von der Seele, funktionierts einen Schritt weiter.

Mit der Anleitung von [hier](https://docs.spring.io/spring-native/docs/0.12.x/reference/htmlsingle/#_with_code_native_image_code) und dem angepassten Entrypoint (die Datei heisst ja `ApplicationKt` und nicht `Application`) funktionierts:
```
> docker run
$ mvn clean package -Pexecutable-jar
$ rm -rf target/native
$ mkdir -p target/native
$ cd target/native
$ jar -xvf ../ahnenwin-2-gedcom-1.3-SNAPSHOT.jar >/dev/null 2>&1
$ cp -R META-INF BOOT-INF/classes
$ native-image -H:Name=my-app -cp BOOT-INF/classes:`find BOOT-INF/lib | tr '\n' ':'` -H:Class=de.ng.ahnenwin2gedcom.ApplicationKt -H:+ReportExceptionStackTraces
```

Und damit war auch klar, dass es im `pom.xml` angepasst werden muss und damit funktioniert dann auch das `native-image` profile. Wenn ichs zum Laufen bekommen habe, stell ich gern einen PR.

Leider stuerzt die App mit dem test.hej im gleichen Verzeichnis noch ab mit
```
Exception in thread "main" java.nio.charset.UnsupportedCharsetException: windows-1252
        at java.base@11.0.20/java.nio.charset.Charset.forName(Charset.java:529)
        at de.ng.ahnenwin2gedcom.hej.HejReader.read(HejReader.kt:14)
        at de.ng.ahnenwin2gedcom.ApplicationKt.mapHejToGedcomFile(Application.kt:26)
        at de.ng.ahnenwin2gedcom.ApplicationKt.mapAllHejFilesToGedcomInCurrentDir(Application.kt:19)
        at de.ng.ahnenwin2gedcom.ApplicationKt.main(Application.kt:11)
        at de.ng.ahnenwin2gedcom.ApplicationKt.main(Application.kt)
```

**Comment by pythklas** [comment]
Hallo x29a!

Danke für dein Interesse an dem Projekt!
Ich werde mir das morgen mal anschauen.
Ich habe es selber ewig nicht mehr gebaut, bin aber sehr daran interessiert, dass es funktioniert und werde dann Feedback geben!

VG pythklas

**Comment by pythklas** [comment]
Ah, mein Kommentar bezog sich noch auf den initialen Post. Freut mich, dass es jetzt baut und bin gespannt, wie weit du kommst.

Halte mich hier gerne auf dem Laufenden, dann werd ich mir das morgen anschauen :)

**Comment by x29a** [comment]
Danke @pythklas fuer deine schnelle Reaktion, mittels https://github.com/oracle/graal/issues/2900 habe ich es nun zum bauen bekommen und er hat mir gleiche jede Menge Fehler im HEJ um die Ohren gehauen, da muss ich wohl per Hand ran um die zu beheben,damit er das GED schreibt.

Ich werd mal einen PR mit meinen Findings stellen, kannst dir ja ueberlegen ob es zum Projekt passt und ggf anderen hilft.

**Comment by x29a** [comment]
Also es baut und laeuft, ich habe alle Fehler in der errors.log bereinigt, bekomme aber immernoch diesen Fehler:
```
Exception in thread "main" org.gedcom4j.exception.GedcomWriterException: Cannot write file - 1 error(s) found during validation requiring repair.  Review the validation findings to determine root cause.
        at org.gedcom4j.writer.GedcomWriter.emit(GedcomWriter.java:488)
        at org.gedcom4j.writer.GedcomWriter.write(GedcomWriter.java:446)
        at org.gedcom4j.writer.GedcomWriter.write(GedcomWriter.java:431)
        at org.gedcom4j.writer.GedcomWriter.write(GedcomWriter.java:469)
        at de.ng.ahnenwin2gedcom.ApplicationKt.mapHejToGedcomFile(Application.kt:29)
        at de.ng.ahnenwin2gedcom.ApplicationKt.mapAllHejFilesToGedcomInCurrentDir(Application.kt:19)
        at de.ng.ahnenwin2gedcom.ApplicationKt.main(Application.kt:11)
        at de.ng.ahnenwin2gedcom.ApplicationKt.main(Application.kt)
```
Wo schaue ich diese validation findings denn nach?

**Comment by pythklas** [comment]
Die Validation-Findings nachzuschauen ist leider sehr eklig und man muss mit dem Debugger ran. Bei der Entwicklung des Tools ist mir bereits aufgefallen, dass die Gedcom-Library, die ich einsetze, irgendwelche Validierungen beim schreiben des Gedcom-Files macht, aber nicht loggt, welche Validierung fehlgeschlagen ist.

Ich schau mir an, ob man die Validation-Findings der Library loggen kann und melde mich, wenn ich was rausgefunden habe. 

Alternativ könntest du mir dein .hej-File zum Debuggen bereitstellen. Ich gehe damit natürlich streng vertraulich um und lösche die Datei, sobald ich mit dem Debuggen fertig bin. [letzten Part gelöscht]

**Comment by pythklas** [comment]
Check mal diesen Branch aus und bau dir die Anwendung damit neu:
https://github.com/pythklas/ahnenwin2gedcom/tree/feature/gedcom-validation-logging
Ich habe mir die Library nochmal angesehen und rausgefunden, wie man die Validations loggen kann.

**Comment by x29a** [comment]
@pythklas wow, starkes finding, das hilft mir auf jedenfall, damit kann ich weiter bereinigen! danke!

mir ist auf dem branch aufgefallen, dass die `errors.log` zwar angelegt wird, aber mit den validation results nicht befuellt wird, ist das gewollt oder noch Restarbeit?

**Comment by pythklas** [comment]
Das ist wohl noch Restarbeit :)

**Comment by x29a** [comment]
Danke fuer den Support, das Problem "Bauen unter Linux" (und sonstwo ;)) wurde geloest, deswegen schliesse ich den Issue.
